services:
  database:
    image: 'docker.io/library/postgres:17@sha256:8a56bef4c60bef3d26193cb9d810fce93def8fd0c459f4a9b14240fbd7559a1d'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=transferdemo
      - POSTGRES_PASSWORD=transferdemo
      - POSTGRES_DB=transferdemo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }