services:
  database:
    image: 'docker.io/library/postgres:17@sha256:6cf6142afacfa89fb28b894d6391c7dcbf6523c33178bdc33e782b3b533a9342'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=transferdemo
      - POSTGRES_PASSWORD=transferdemo
      - POSTGRES_DB=transferdemo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }