services:
  database:
    image: 'docker.io/library/postgres:18@sha256:74935e72241653ca55e0414067e6d8763aceb8a810eb51b452253ec3dcfc4336'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=transferdemo
      - POSTGRES_PASSWORD=transferdemo
      - POSTGRES_DB=transferdemo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }