services:
  database:
    image: 'docker.io/library/postgres:18@sha256:073e7c8b84e2197f94c8083634640ab37105effe1bc853ca4d5fbece3219b0e8'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=transferdemo
      - POSTGRES_PASSWORD=transferdemo
      - POSTGRES_DB=transferdemo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }